{% set version = "0.11.4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-learnr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/learnr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/learnr/learnr_{{ version }}.tar.gz
  sha256: ee64bd88cda6ddec8c9a2a561099461db915f6e99fe27e3c314b748faa1655d4

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-checkmate
    - r-curl
    - r-digest
    - r-ellipsis >=0.2.0.1
    - r-evaluate
    - r-htmltools >=0.3.5
    - r-htmlwidgets
    - r-jsonlite
    - r-knitr >=1.31
    - r-lifecycle
    - r-markdown
    - r-promises
    - r-rappdirs
    - r-renv >=0.8.0
    - r-rlang
    - r-rmarkdown >=1.12.0
    - r-rprojroot
    - r-shiny >=1.0
    - r-withr
  run:
    - r-base
    - r-checkmate
    - r-curl
    - r-digest
    - r-ellipsis >=0.2.0.1
    - r-evaluate
    - r-htmltools >=0.3.5
    - r-htmlwidgets
    - r-jsonlite
    - r-knitr >=1.31
    - r-lifecycle
    - r-markdown
    - r-promises
    - r-rappdirs
    - r-renv >=0.8.0
    - r-rlang
    - r-rmarkdown >=1.12.0
    - r-rprojroot
    - r-shiny >=1.0
    - r-withr

test:
  commands:
    - $R -e "library('learnr')"           # [not win]
    - "\"%R%\" -e \"library('learnr')\""  # [win]

about:
  home: https://rstudio.github.io/learnr/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE-2.0.txt
  summary: Create interactive tutorials using R Markdown. Use a combination  of narrative, figures, videos, exercises, and quizzes to create self-paced tutorials for learning about R and R packages.

extra:
  recipe-maintainers:
    - conda-forge/r
    - oblute
    - benhuff

# Package: learnr
# Type: Package
# Title: Interactive Tutorials for R
# Version: 0.9.2.1
# Authors@R: c( person("Barret", "Schloerke", role = c("aut", "cre"), email = "barret@rstudio.com"), person("JJ", "Allaire", role = "aut", email = "jj@rstudio.com"), person("Barbara", "Borges", role = c("aut"), email = "barb.b.ribeiro@gmail.com"), person(family = "RStudio, Inc.", role = "cph"), person(family = "Ajax.org B.V.", role=c("ctb", "cph"), comment= "Ace library"), person("Zeno", "Rocha", role = c("ctb", "cph"), comment = "clipboard.js library"), person("Nick", "Payne", role = c("ctb", "cph"), comment = "Bootbox library"), person("Julie", "Cameron", role = "ctb", comment = "SlickQuiz library"), person(family = "Quicken Loans", role = "cph", comment = "SlickQuiz library"), person(family = "Mozilla", role = c("ctb", "cph"), comment = "localforage library") )
# Description: Create interactive tutorials using R Markdown. Use a combination  of narrative, figures, videos, exercises, and quizzes to create self-paced tutorials for learning about R and R packages.
# License: Apache License 2.0 | file LICENSE
# URL: https://rstudio.github.io/learnr/
# BugReports: https://github.com/rstudio/learnr/issues
# Imports: utils, parallel, withr, rappdirs, rprojroot, jsonlite, htmltools (>= 0.3.5), htmlwidgets, evaluate, knitr (>= 1.14), markdown, shiny (>= 1.0), rmarkdown (>= 1.8)
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.0.1
# Suggests: testthat
# NeedsCompilation: no
# Packaged: 2018-06-28 21:36:45 UTC; jcheng
# Author: Barret Schloerke [aut, cre], JJ Allaire [aut], Barbara Borges [aut], RStudio, Inc. [cph], Ajax.org B.V. [ctb, cph] (Ace library), Zeno Rocha [ctb, cph] (clipboard.js library), Nick Payne [ctb, cph] (Bootbox library), Julie Cameron [ctb] (SlickQuiz library), Quicken Loans [cph] (SlickQuiz library), Mozilla [ctb, cph] (localforage library)
# Maintainer: Barret Schloerke <barret@rstudio.com>
# Repository: CRAN
# Date/Publication: 2018-06-29 21:23:13 UTC
