appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: I5Rjd3rfaEql+WTocSGxaEoq68hQqTz7pQuVJKSPRk+AlL59bUJ14VU9B9Xm56KUam7JzY2mk+NDCWPsKIBNb5XxPUH4KemPtZNgl8VNCEdj7yorwc8EhZ819hoXuTZ4lkGIKqRnHjjFPO6wcgufu90+gqf5QpxlkA+m1O4o5DO4O26kO+Tc6liTyQUrnWHm6PlwdHqCTVNWBw0J7tCQSAgdsC0sXLheLSPoVPdRgkqIWncn/umwuqnVqKiAsUzwW6si0rNpYHBcwHvHV+O7Vfq6XS8OV0TH7rV/JxX7FBcq/mOtBL021UrrrE7v9Zs8bwgKksXvCYM89u9WlbY++bD8aKQkjguPBogc0u82bF3WO/MgTPH0ZCgnFxl2fcAc/T0R4lxueumMgN8D3nkB+WmC1BYOj9iEqv8+FZ0bHmpwDM0HcyiwWpJhgaU/v0cLWodfjD6N7fcDO7QWtMgJLDbR5WufuQ1U8ZFWVpLXBsCcLWCrEWEZdSOZFUSkaD7kCZaOsFkiPALNCjFGibBtpjhE0WGOn6rijrjQZm+J/G9tl9H6RUXngZfeDACjSaHt0GHTARv0MBCHvjbXZqZKPNCe3cN1fv0xfEw+0zSVqHGF0PVq//b91m/NYCusxLt15FcGSFM+h5nRHTJseVMrmS+9OKiYSLfcnGVjjSbbBQc=
conda_forge_output_validation: true
